---

  - name: "Fix AppStream repo "
    become: true
    lineinfile:
      path: /etc/yum.repos.d/CentOS-Linux-AppStream.repo
      regexp: '^mirrorlist='
      line: "#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=AppStream&infra=$infra"
  - name: "Add Appstream rebo link"
    become: true
    lineinfile:
      path: /etc/yum.repos.d/CentOS-Linux-AppStream.repo
      regexp: '^#baseurl='
      line: baseurl=http://mirror.marwan.ma/centos/8-stream/AppStream/x86_64/os/
  - name: "Fix BaseOS repo "
    become: true
    lineinfile:
      path: /etc/yum.repos.d/CentOS-Linux-BaseOS.repo
      regexp: '^mirrorlist='
      line: "#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=BaseOS&infra=$infra"
  - name: "Add BaseOS repo link"
    become: true
    lineinfile:
      path: /etc/yum.repos.d/CentOS-Linux-BaseOS.repo
      regexp: '^#baseurl='
      line: baseurl=http://mirror.marwan.ma/centos/8-stream/BaseOS/x86_64/os/
  - name: "Fix Extras repo "
    become: true
    lineinfile:
      path: /etc/yum.repos.d/CentOS-Linux-Extras.repo
      regexp: '^mirrorlist='
      line: "#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra"
  - name: "Add Extras repo link"
    become: true
    lineinfile:
      path: /etc/yum.repos.d/CentOS-Linux-Extras.repo
      regexp: '^#baseurl='
      line: baseurl=http://mirror.marwan.ma/centos/8-stream/extras/x86_64/os/

  - name: "install xcat dependancies"
    become: true
    yum:
      name:
        - gcc
        - make
      state: present
    
  - name: "Set hostname"
    become: true
    hostname:
      name: xcat.cluster.com
      use: systemd
  
  - name: "create directory for xcat installer"
    file:
      path: /home/beshoy/xcat-installer
      state: directory
      owner: beshoy
      group: beshoy
  
  - name: "check if xcat installer is downloaded"
    stat:
      path: /home/beshoy/xcat-installer/go-xcat
    register: installer_check
      
  - name: "download xcat installer"
    uri:
      url: https://raw.githubusercontent.com/xcat2/xcat-core/master/xCAT-server/share/xcat/tools/go-xcat
      dest: /home/beshoy/xcat-installer/go-xcat
      mode: '0740'
    when: not installer_check.stat.exists

  - name: "check if xcat is installed"
    stat:
      path: /etc/xcat
    register: check_result
  - debug: msg={{check_result}}

  - name: "install xCAT"
    become: true
    shell: /home/beshoy/xcat-installer/go-xcat install -y
    when: not check_result.stat.exists

  


    
